### ISSUE TITLE
DOI minting button

### ISSUE THREAD

**Issue by volkerblum** [HybriD3-database/MatD3#11]
One more question concerns the "mint DOI" button in the HybriD3 instance of MatD3. 

This appears for data sets even if one is not logged in, not just for the creator / owner of the data set. I believe this button should not appear unless one is the creator of the data set or perhaps the administrator of the entire database. Can this be changed, and where?

**Comment by raullaasner** [comment]
This can be changed. First place is [here](https://github.com/HybriD3-database/MatD3/blob/6700447ceac9f7e3b3188438ebd4384c06e997f8/materials/templates/materials/dataset_contents.html#L425) in the template, so that it wouldn't appear to the general public, and the second place is [here](https://github.com/HybriD3-database/MatD3/blob/6700447ceac9f7e3b3188438ebd4384c06e997f8/materials/views.py#L1152), where it should be checked that the user is the owner of the data set. As with the other issue, I can get back to you within the next few days.

As a comment, currently only users that have "staff" status can mint a DOI (but this can be narrowed to just data set owners). Even though the button is visible to everybody, it won't work unless the user has the right privileges.
